-- alter column type ONLY after the tables are created in pgADMIN.  run in pgADMIN
ALTER TABLE listings
ALTER COLUMN zipcode TYPE VARCHAR; 

ALTER TABLE sfmasszip
ALTER COLUMN land_area_sqmeters TYPE VARCHAR;

SELECT * FROM listings
LEFT JOIN sfmasszip
ON listings.zipcode = sfmasszip.zip_code;

 






--change column type date--not used
ALTER TABLE listings 
ALTER COLUMN first_review SET DATA TYPE date
      USING to_date(first_review, 'mm-dd-yyyy');

ALTER TABLE listings
ALTER COLUMN host_is_superhost TYPE VARCHAR; 


--not used
SELECT listings.id,
	listings.host_since,
	listings.host_response_time,
	listings.host_response_rate,
	listings.host_is_superhost,
	listings.host_listings_count,
	listings.host_total_listings_count,
	listings.host_identity_verified,
 	listings.neighbourhood_cleansed,
	listings.zipcode,
	listings.latitude,
	listings.longitude,
	sfmasszip.land_area_sqmeters	
FROM listings
LEFT JOIN sfmasszip
ON listings.zipcode = sfmasszip.zip_code;




-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.listings
(
    id bigint,
    host_since date,
    host_response_time text,
    host_response_rate text,
    host_is_superhost character varying,
    host_listings_count bigint,
    host_total_listings_count bigint,
    host_identity_verified bigint,
    neighbourhood_cleansed text,
    zipcode character varying,
    latitude double precision,
    longitude double precision,
    property_type text,
    room_type text,
    accommodates bigint,
    bathrooms double precision,
    bedrooms bigint,
    beds bigint,
    price bigint,
    minimum_nights bigint,
    maximum_nights bigint,
    calendar_updated text,
    availability_30 bigint,
    availability_60 bigint,
    availability_90 bigint,
    availability_365 bigint,
    number_of_reviews bigint,
    number_of_reviews_ltm bigint,
    first_review date,
    review_scores_rating double precision,
    review_scores_accuracy double precision,
    review_scores_cleanliness double precision,
    review_scores_checkin double precision,
    review_scores_communication double precision,
    review_scores_location double precision,
    review_scores_value double precision,
    instant_bookable bigint,
    calculated_host_listings_count bigint,
    calculated_host_listings_count_entire_homes bigint,
    calculated_host_listings_count_private_rooms bigint,
    calculated_host_listings_count_shared_rooms bigint,
    reviews_per_month double precision,
    host_days_active bigint,
    time_since_first_review text,
    time_since_last_review bigint
);

CREATE TABLE IF NOT EXISTS public.sfmasszip
(
    index bigint,
    zip_code character varying,
    land_area_sqmeters character varying,
    land_area_sqmiles bigint,
    land_area_sqkilometers bigint
);

ALTER TABLE public.sfmasszip
    ADD FOREIGN KEY (zip_code)
    REFERENCES public.listings (zipcode)
    NOT VALID;

END;