-- alter column type ONLY after the tables are created in pgADMIN.  run in pgADMIN
ALTER TABLE listings
ALTER COLUMN zipcode TYPE VARCHAR; 

ALTER TABLE sfmasszip
ALTER COLUMN zip_code TYPE VARCHAR; 


ALTER TABLE sfmasszip
ALTER COLUMN land_area_sqmeters TYPE VARCHAR;

-- join both tables, 
SELECT * FROM listings
LEFT JOIN sfmasszip
ON listings.zipcode = sfmasszip.zip_code;



--change column type date--not used
alter table listings 
alter first_review type date using(first_review::date)

alter table listings 
alter host_since type date using(host_since::date)

select * from listings;

ALTER TABLE listings 
ALTER COLUMN first_review SET DATA TYPE date
      USING to_date(first_review, 'mm-dd-yyyy');

ALTER TABLE listings
ALTER COLUMN host_is_superhost TYPE VARCHAR; 


--not used
SELECT listings.id,
	listings.host_since,
	listings.host_response_time,
	listings.host_response_rate,
	listings.host_is_superhost,
	listings.host_listings_count,
	listings.host_total_listings_count,
	listings.host_identity_verified,
 	listings.neighbourhood_cleansed,
	listings.zipcode,
	listings.latitude,
	listings.longitude,
	sfmasszip.land_area_sqmeters	
FROM listings
LEFT JOIN sfmasszip
ON listings.zipcode = sfmasszip.zip_code;




-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.listings
(
    id integer,
    host_since date,
    host_response_time text,
    host_response_rate text,
    host_is_superhost character varying,
    host_listings_count integer,
    host_total_listings_count integer,
    host_identity_verified integer,
    neighbourhood_cleansed text,
    zipcode character varying,
    latitude double precision,
    longitude double precision,
    property_type text,
    room_type text,
    accommodates integer,
    bathrooms double precision,
    bedrooms integer,
    beds integer,
    price integer,
    minimum_nights integer,
    maximum_nights integer,
    calendar_updated text,
    availability_30 integer,
    availability_60 integer,
    availability_90 integer,
    availability_365 integer,
    number_of_reviews integer,
    number_of_reviews_ltm integer,
    first_review date,
    review_scores_rating double precision,
    review_scores_accuracy double precision,
    review_scores_cleanliness double precision,
    review_scores_checkin double precision,
    review_scores_communication double precision,
    review_scores_location double precision,
    review_scores_value double precision,
    instant_bookable integer,
    calculated_host_listings_count integer,
    calculated_host_listings_count_entire_homes integer,
    calculated_host_listings_count_private_rooms integer,
    calculated_host_listings_count_shared_rooms integer,
    reviews_per_month double precision,
    host_days_active integer,
    time_since_first_review text,
    time_since_last_review integer
);

CREATE TABLE IF NOT EXISTS public.sfmasszip
(
    index integer,
    zip_code character varying,
    land_area_sqmeters character varying,
    land_area_sqmiles integer,
    land_area_sqkilometers integer
);

ALTER TABLE public.sfmasszip
    ADD FOREIGN KEY (zip_code)
    REFERENCES public.listings (zipcode)
    NOT VALID;

END;